project:
  type: website
  output-dir: "."

# Can customize this section with options from the following page:
# https://quarto.org/docs/websites/website-navigation.html
website:
  title: "Quantifying effort"
  sidebar:
    style: "docked"
    logo: "docs/images/Buffalo_Sabres_Logo.png"
    search: true
        
format:
  html:
    smooth-scroll: true
    toc: true
    toc-expand: true
    toc-depth: 2  
    toc-location: left
    toc-title: "Contents"
    date: "July 25, 2025"
    published-title: false
    bibliography: "bib/library.bib" # Edit the contents of this file
    highlight-style: arrow
    theme: cosmo
    fontsize: 13pt
    css: styles.css
