---
title: "Quantifying Effort in American Football"
author: "Emily Shteynberg, Luke Snavely, Sheryl Solorzano"
format:
  revealjs:
    theme: theme.scss
    smaller: true
    incremental: true
    math: mathjax
    slide-number: c/t
    embed-resources: true
    code-line-numbers: false
    linestretch: 1.25
    html-math-method:
      method: mathjax
---

## Introduction:

* Quantifying effort for running backs from the NFL 2022 season
   
* Why is this important?
   - Traditional stats miss the "how" behind play values such as yards gained, expected added points, etc.
   - Evaluating running backs' effort and performance 

## Data: 2022 NFL Season

* Data description
   - Game, play, player, tracking data from Weeks 1-9 [^1]
   - Running plays where a running back (RB) is the ball carrier
   - Trimmed each play to frames between handoff and end of play

* Relevant data pre-processing steps
  - Calculating fatigue (back up vs starting running backs)
  - 

## Plan of Action

* Define research question and scope ✅

* Data cleaning and preprocessing, EDA ✅

* Select effort metric(s) ✅

* Figure out non-linear quantile regression for expected AS and AKE profile curves of a running back 

* Use chosen metric(s) to answer questions related to effort (residual effort, tackle outcome probabilities, minimum required effort per play, etc) 

* Interpret results, complete report and presentation

## Presenting Completed Steps

- AS 

- 

## Plan of action


