---
title: "Quantifying Effort in American Football"
author: "Emily Shteynberg, Luke Snavely, Sheryl Solorzano"
format:
  revealjs:
    theme: theme.scss
    smaller: true
    incremental: true
    math: mathjax
    slide-number: c/t
    embed-resources: true
    code-line-numbers: false
    linestretch: 1.25
    html-math-method:
      method: mathjax
      url: "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"
---

## Background and Motivation

* Not all rushing yards are equal 

* Traditional stats miss the "how" behind yards gained

* Previous research has explored athletes reaching theoretical max capacity [^1]

* Can we "measure" effort using tracking data?

* Multiple ways of evaluating effort 

  - Intangible and subjective
  - Depends on player position, defense faced, game context, snap count/play volume, play call/assignment

[^1]: Morin, et al. 2021. “Individual Acceleration-Speed Profile in-Situ: A Proof of Concept in Professional Football Players.” Journal of Biomechanics 123: 110524.


## Our Data: 2022 NFL Season 

* Game, play, player, tracking data from Weeks 1-9 [^1]

* Running plays where a running back (RB) is the ball carrier

* Trimmed each play to frames between handoff and end of play

[^1]: Courtesy of NFL Big Data Bowl 2025

## Morin, et al. tells us how

## Plan of action

* Define research question and scope ✅

* Data cleaning and preprocessing, EDA ✅

* Select effort metric(s)

* Use chosen metric(s) to answer questions related to effort (residual effort, tackle outcome probabilities, minimum required effort per play, etc)

* Interpret results, complete report and presentation


# Appendix 


